package exception;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;


public class ExceptionTest2 {
	
	private int dan;
	
	public void input() throws IOException{
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		System.out.print("단 입력: ");
		dan = Integer.parseInt(br.readLine());
	}
	public void output() {
		if(dan<10)
		for(int i = 1; i<10; i++) {
			System.out.println(dan+"*"+i+"= "+dan*i);
		}
		else //System.out.println("범위 초과(2~9까지 가능)");
			
			//개발자가 강제로 Exception발생 시키는 방법.  throws 는 에러를 잡는거 throw는 에러를 발생시키는거
			try {
				throw new Exception();
			}catch(Exception e) {
				e.pirntStackTrace();
			}
	}
	public static void main(String[] args) throws IOException{
		
		ExceptionTest2 e = new ExceptionTest2();
		e.input();
		e.output();
	}
}
