package exception;

import java.util.Scanner;

public class ExceptionTest {
	
	public static void main(String[] args) {
		for(String data : args) {
			System.out.println(data);
		}
		
		Scanner scan = new Scanner(System.in);
		System.out.print("숫자 입력: ");
		try{
			int num2 = scan.nextInt();
		}catch (ArithmeticException e) {
			System.out.println("0이 입력될수 없습니다.");
		}
		
		int num = Integer.parseInt(args[0]);
		System.out.println("num: "+num+"num2: "+num2);
		System.out.println(num+"/"+num2+"= "+num/num2);
		
		
	}
}
