package exception;

import java.util.Scanner;

public class ExceptionTest {
	
	public static void main(String[] args) {
		for(String data : args) {
			System.out.println(data);
		}
		
		Scanner scan = new Scanner(System.in);
		int num = Integer.parseInt(args[0]);
		System.out.print("숫자 입력: ");
		
		
		try{
			int num2 = scan.nextInt();
			System.out.println("num: "+num+"  num2: "+num2);
			System.out.println(num+"/"+num2+"= "+num/num2);
		}catch (ArithmeticException e) {
			System.out.println("0으로 나눌수없습니다..");
		}catch (InputMismatchException e) {
			System.out.println("숫자만 입력하시오");
		}
		
		
		
		
	}
}
